# Any packages - have issues or vulnerabilities(scan) in them such as in requirements.txt we have flask. let's say we have flask==3.1.0 and dependency scan will tell me if there any issue or not.

name: Dependency Scan